# Chimeric receptors simulations - Assertion testing

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os

#from IPython.display import display

# this is needed only if maboss is not seen by Jupyter
path_dev = os.path.expanduser("~/Documents/MaBoSS/pyMaBoSS")
if path_dev not in sys.path:
    sys.path.insert(0, path_dev)
        
import maboss
from maboss import temporal_logic as tl

### Sanity test (apoptosis and prolif cannot happen at the same time)

In [2]:
assertions_list = ["P(fp:Apoptosis,proliferation) >= 0.09 [ ] [ ] [ comb ]",
                   "P(node:Th1) >= 0.4",
                   "P(node:Apoptosis) >= 0.09",]

In [3]:
bnd = "model_Tcell.bnd"
cfg = "model_Tcell.cfg"

nodes = list(maboss.load(bnd,cfg).network.keys())
#print(nodes)

ON = [0,1]
OFF = [1,0]
RANDOM = [0.5, 0.5]

all_nodes_random_init = [{'node':node,'istate':RANDOM} for node in nodes]
#print(all_nodes_off)

# initial conditions
i_c_TME = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON},
    {'node':'TIM3_L','istate':ON},
    {'node':'IFNG_L','istate':ON},
    {'node':'IL2_L','istate':ON},
    {'node':'IL4_L','istate':ON},
    {'node':'TGFB_L','istate':ON},
    {'node':'L41BB','istate':ON},
    {'node':'FAS_L','istate':ON},
    {'node':'TIGIT_L','istate':ON},
    {'node':'PD1_L','istate':ON},
    {'node':'IL7_L','istate':ON},
    {'node':'CD80_86','istate':ON},
    {'node':'IL12_L','istate':ON},
    {'node':'IL27_L','istate':ON},
    {'node':'ICOS_L','istate':ON},
]

i_c_MM = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON},
    {'node':'TIM3_L','istate':ON},
    {'node':'IFNG_L','istate':ON},
    {'node':'IL2_L','istate':ON},
    {'node':'IL4_L','istate':ON},
    {'node':'TGFB_L','istate':ON},
    {'node':'L41BB','istate':ON},
    {'node':'FAS_L','istate':ON},
    {'node':'TIGIT_L','istate':ON},
    {'node':'PD1_L','istate':ON}
]

i_c_antigen = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON}
]

# CD4
# initial states to have types of cells
CD4 = all_nodes_random_init + [{'node':'iden_CD4','istate':ON}]
is_CART =  CD4 + i_c_TME + [{'node':'iden_CAR','istate':ON}]
is_Tcell = [{'node':'iden_abTCR','istate':ON}] + CD4
is_TEG001 = [{'node':'iden_gdTCR','istate':ON},] + CD4
is_TEG103 = [{'node':'iden_gdTCR','istate':ON},{'node':'iden_R103','istate':ON}] + CD4
is_TEG103_trunc = [{'node':'iden_TR103','istate':ON},{'node':'iden_gdTCR','istate':ON}] + CD4
is_NKG2D_CD28 = [{'node':'iden_NKCD28','istate':ON}, {'node':'iden_gdTCR','istate':ON}] + CD4
is_NKG2D_41BB = [{'node':'iden_NK41BB','istate':ON}, {'node':'iden_gdTCR','istate':ON}] + CD4

### Run the simulations and the querying
if you want to use 2 initial conditions use `list1.extend(list2)`
**eg: CART with TME : `tl.MaBoSSEvaluator.querying(assertions,cfg,bnd,is_CART.extend(i_c_TME)`**

In [4]:
ouput_setting = ["Apoptosis","proliferation","Th1"]
res_CART = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_CART,ouput_setting)
res_Tcell = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_Tcell,ouput_setting)
res_TEG001 = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_TEG001,ouput_setting)
res_TEG103 = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_TEG103,ouput_setting)
res_TEG103_trunc = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_TEG103_trunc,ouput_setting)
res_NKG2D_CD28 = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_NKG2D_CD28,ouput_setting)
res_NKG2D_41BB = tl.MaBoSSEvaluator.querying(assertions_list,cfg,bnd,is_NKG2D_41BB,ouput_setting)

Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !

### Results diplay

In [5]:
#list_all_res = res_CART + res_Tcell + res_TEG001 + res_TEG103 + res_TEG103_trunc + res_NKG2D_CD28 + res_NKG2D_41BB
#list_title = ["CART","Tcell","TEG001","TEG103","TEG103_trunc","NKG2D_CD28","NKG2D_41BB"]

tl.Visualiser(list_queries=assertions_list, list_of_results=res_CART).display_results_and_queries("CART + TME")

CART + TME
Query 1 : P(fp:Apoptosis,proliferation) >= 0.09 [ ] [ ] [ comb ]

   P_cumul(Apoptosis,proliferation)  Comparison value
0                               0.0             False

Query 2 : P(node:Th1) >= 0.4

   Time     Th1
0   0.0  0.4436

Query 3 : P(node:Apoptosis) >= 0.09

       Time  Apoptosis
0       0.0     0.5037
1       0.5     0.4974
2       1.0     0.4834
3       1.5     0.4691
4       2.0     0.4554
5       2.5     0.4500
6       3.0     0.4421
7       3.5     0.4344
8       4.0     0.4270
9       4.5     0.4202
10      5.0     0.4094
11      5.5     0.3992
12      6.0     0.3911
13      6.5     0.3839
14      7.0     0.3745
15      7.5     0.3666
16      8.0     0.3592
17      8.5     0.3500
18      9.0     0.3418
19      9.5     0.3331
20     10.0     0.3241
21     10.5     0.3128
22     11.0     0.3029
23     11.5     0.2937
24     12.0     0.2841
25     12.5     0.2737
26     13.0     0.2646
27     13.5     0.2562
28     14.0     0.2493
29     14.5     0.2419
30     15.0     0.2347
31     15.5     0.2291
32     16.0     0.2238
33     16.5     0.2185
34     17.0     0.2141
35     17.5     0.2105
36     18.0     0.2056
37     18.5     0.2017
38     19.0     0.1975
39     19.5     0.1953
40     20.0     0.1936
41     20.5     0.1921
42     21.0     0.1909
43     21.5     0.1898
44     22.0     0.1890
45     22.5     0.1874
46     23.0     0.1860
47     23.5     0.1852
48     24.0     0.1841
49     24.5     0.1825
50     25.0     0.1821
51     25.5     0.1818
52     26.0     0.1819
53     26.5     0.1817
54     27.0     0.1813
55     27.5     0.1803
56     28.0     0.1804
57     28.5     0.1802
58     29.0     0.1802
59     29.5     0.1804
60     30.0     0.1800
61     30.5     0.1798
62     31.0     0.1792
63     31.5     0.1788
64     32.0     0.1789
65     32.5     0.1788
66     33.0     0.1781
67     33.5     0.1781
68     34.0     0.1784
69     34.5     0.1784
70     35.0     0.1785
71     35.5     0.1785
72     36.0     0.1784
73     36.5     0.1788
74     37.0     0.1789
75     37.5     0.1791
76     38.0     0.1788
77     38.5     0.1784
78     39.0     0.1789
79     39.5     0.1794
80     40.0     0.1789
81     40.5     0.1783
82     41.0     0.1781
83     41.5     0.1780
84     42.0     0.1784
85     42.5     0.1778
86     43.0     0.1778
87     43.5     0.1780
88     44.0     0.1777
89     44.5     0.1776
90     45.0     0.1774
91     45.5     0.1772
92     46.0     0.1771
93     46.5     0.1771
94     47.0     0.1766
95     47.5     0.1763
96     48.0     0.1760
97     48.5     0.1761
98     49.0     0.1763
99     49.5     0.1758
100    50.0     0.1757
101    50.5     0.1756
102    51.0     0.1752
103    51.5     0.1755
104    52.0     0.1761
105    52.5     0.1764
106    53.0     0.1765
107    53.5     0.1763
108    54.0     0.1765
109    54.5     0.1762
110    55.0     0.1765
111    55.5     0.1768
112    56.0     0.1769
113    56.5     0.1773
114    57.0     0.1769
115    57.5     0.1767
116    58.0     0.1765
117    58.5     0.1767
118    59.0     0.1767
119    59.5     0.1763
120    60.0     0.1760
121    60.5     0.1755
122    61.0     0.1754
123    61.5     0.1753
124    62.0     0.1755
125    62.5     0.1752
126    63.0     0.1750
127    63.5     0.1750
128    64.0     0.1748
129    64.5     0.1748
130    65.0     0.1751
131    65.5     0.1753
132    66.0     0.1756
133    66.5     0.1758
134    67.0     0.1756
135    67.5     0.1753
136    68.0     0.1749
137    68.5     0.1753
138    69.0     0.1752
139    69.5     0.1751
140    70.0     0.1750
141    70.5     0.1751
142    71.0     0.1749
143    71.5     0.1745
144    72.0     0.1745
145    72.5     0.1743
146    73.0     0.1742
147    73.5     0.1742
148    74.0     0.1741
149    74.5     0.1738
150    75.0     0.1737
151    75.5     0.1737
152    76.0     0.1738
153    76.5     0.1740
154    77.0     0.1742
155    77.5     0.1741
156    78.0     0.1739
157    78.5     0.1739
158    79.0     0.1738
159    79.5     0.1738
160    80.0     0.1739
161    80.5     0.1737
162    81.0     0.1735
163    81.5     0.1736
164    82.0     0.1738
165    82.5     0.1737
166    83.0     0.1738
167    83.5     0.1740
168    84.0     0.1741
169    84.5     0.1739
170    85.0     0.1739
171    85.5     0.1743
172    86.0     0.1744
173    86.5     0.1748
174    87.0     0.1750
175    87.5     0.1748
176    88.0     0.1743
177    88.5     0.1743
178    89.0     0.1743
179    89.5     0.1738
180    90.0     0.1735
181    90.5     0.1737
182    91.0     0.1740
183    91.5     0.1743
184    92.0     0.1748
185    92.5     0.1751
186    93.0     0.1751
187    93.5     0.1748
188    94.0     0.1747
189    94.5     0.1747
190    95.0     0.1747
191    95.5     0.1746
192    96.0     0.1744
193    96.5     0.1741
194    97.0     0.1740
195    97.5     0.1736
196    98.0     0.1734
197    98.5     0.1737
198    99.0     0.1738
199    99.5     0.1738
200   100.0     0.1736
201   100.5     0.1734
202   101.0     0.1733
203   101.5     0.1733
204   102.0     0.1733
205   102.5     0.1735
206   103.0     0.1736
207   103.5     0.1735
208   104.0     0.1734
209   104.5     0.1731
210   105.0     0.1733
211   105.5     0.1734
212   106.0     0.1733
213   106.5     0.1736
214   107.0     0.1736
215   107.5     0.1737
216   108.0     0.1736
217   108.5     0.1737
218   109.0     0.1737
219   109.5     0.1736
220   110.0     0.1735
221   110.5     0.1738
222   111.0     0.1740
223   111.5     0.1741
224   112.0     0.1741
225   112.5     0.1738
226   113.0     0.1735
227   113.5     0.1733
228   114.0     0.1734
229   114.5     0.1733
230   115.0     0.1732
231   115.5     0.1733
232   116.0     0.1733
233   116.5     0.1731
234   117.0     0.1732
235   117.5     0.1732
236   118.0     0.1732
237   118.5     0.1732
238   119.0     0.1732
239   119.5     0.1731
240   120.0     0.1730
241   120.5     0.1731
242   121.0     0.1733
243   121.5     0.1733
244   122.0     0.1736
245   122.5     0.1735
246   123.0     0.1736
247   123.5     0.1736
248   124.0     0.1736
249   124.5     0.1737
250   125.0     0.1740
251   125.5     0.1741
252   126.0     0.1741
253   126.5     0.1740
254   127.0     0.1738
255   127.5     0.1736
256   128.0     0.1736
257   128.5     0.1734
258   129.0     0.1734
259   129.5     0.1734
260   130.0     0.1736
261   130.5     0.1736
262   131.0     0.1737
263   131.5     0.1736
264   132.0     0.1736
265   132.5     0.1737
266   133.0     0.1737
267   133.5     0.1733
268   134.0     0.1736
269   134.5     0.1738
270   135.0     0.1737
271   135.5     0.1738
272   136.0     0.1738
273   136.5     0.1736
274   137.0     0.1734
275   137.5     0.1733
276   138.0     0.1732
277   138.5     0.1735
278   139.0     0.1737
279   139.5     0.1737
280   140.0     0.1737
281   140.5     0.1739
282   141.0     0.1740
283   141.5     0.1741
284   142.0     0.1740
285   142.5     0.1739
286   143.0     0.1738
287   143.5     0.1737
288   144.0     0.1737
289   144.5     0.1739
290   145.0     0.1740
291   145.5     0.1742
292   146.0     0.1742
293   146.5     0.1740
294   147.0     0.1735
295   147.5     0.1735
296   148.0     0.1737
297   148.5     0.1735
298   149.0     0.1733
299   149.5     0.1734
300   150.0     0.1733
301   150.5     0.1729
302   151.0     0.1730
303   151.5     0.1731
304   152.0     0.1728
305   152.5     0.1728
306   153.0     0.1728
307   153.5     0.1726
308   154.0     0.1726
309   154.5     0.1726
310   155.0     0.1725
311   155.5     0.1730
312   156.0     0.1731
313   156.5     0.1732
314   157.0     0.1733
315   157.5     0.1733
316   158.0     0.1730
317   158.5     0.1730
318   159.0     0.1731
319   159.5     0.1731
320   160.0     0.1731
321   160.5     0.1733
322   161.0     0.1733
323   161.5     0.1733
324   162.0     0.1734
325   162.5     0.1732
326   163.0     0.1730
327   163.5     0.1727
328   164.0     0.1726
329   164.5     0.1725
330   165.0     0.1726
331   165.5     0.1729
332   166.0     0.1731
333   166.5     0.1731
334   167.0     0.1730
335   167.5     0.1731
336   168.0     0.1734
337   168.5     0.1736
338   169.0     0.1733
339   169.5     0.1732
340   170.0     0.1733
341   170.5     0.1731
342   171.0     0.1728
343   171.5     0.1728
344   172.0     0.1729
345   172.5     0.1728
346   173.0     0.1727
347   173.5     0.1728
348   174.0     0.1727
349   174.5     0.1727
350   175.0     0.1726
351   175.5     0.1729
352   176.0     0.1729
353   176.5     0.1734
354   177.0     0.1736
355   177.5     0.1737
356   178.0     0.1737
357   178.5     0.1737
358   179.0     0.1739
359   179.5     0.1740
360   180.0     0.1740
361   180.5     0.1738
362   181.0     0.1738
363   181.5     0.1737
364   182.0     0.1737
365   182.5     0.1738
366   183.0     0.1738
367   183.5     0.1736
368   184.0     0.1734
369   184.5     0.1734
370   185.0     0.1735
371   185.5     0.1737
372   186.0     0.1738
373   186.5     0.1739
374   187.0     0.1741
375   187.5     0.1742
376   188.0     0.1742
377   188.5     0.1741
378   189.0     0.1738
379   189.5     0.1739
380   190.0     0.1736
381   190.5     0.1733
382   191.0     0.1729
383   191.5     0.1731
384   192.0     0.1730
385   192.5     0.1731
386   193.0     0.1732
387   193.5     0.1732
388   194.0     0.1730
389   194.5     0.1730
390   195.0     0.1732
391   195.5     0.1728
392   196.0     0.1727
393   196.5     0.1729
394   197.0     0.1731
395   197.5     0.1734
396   198.0     0.1733
397   198.5     0.1734
398   199.0     0.1736
399   199.5     0.1739
400   200.0     0.1738
401   200.5     0.1736
402   201.0     0.1737
403   201.5     0.1734
404   202.0     0.1733
405   202.5     0.1731
406   203.0     0.1730
407   203.5     0.1731
408   204.0     0.1728
409   204.5     0.1728
410   205.0     0.1731
411   205.5     0.1731
412   206.0     0.1732
413   206.5     0.1731
414   207.0     0.1730
415   207.5     0.1732
416   208.0     0.1733
417   208.5     0.1733
418   209.0     0.1735
419   209.5     0.1734
420   210.0     0.1730
421   210.5     0.1731
422   211.0     0.1730
423   211.5     0.1727
424   212.0     0.1728
425   212.5     0.1729
426   213.0     0.1729
427   213.5     0.1728
428   214.0     0.1727
429   214.5     0.1726
430   215.0     0.1727
431   215.5     0.1727
432   216.0     0.1725
433   216.5     0.1724
434   217.0     0.1721
435   217.5     0.1722
436   218.0     0.1723
437   218.5     0.1725
438   219.0     0.1727
439   219.5     0.1727
440   220.0     0.1727
441   220.5     0.1727
442   221.0     0.1726
443   221.5     0.1726
444   222.0     0.1727
445   222.5     0.1731
446   223.0     0.1728
447   223.5     0.1726
448   224.0     0.1725
449   224.5     0.1726
450   225.0     0.1726
451   225.5     0.1727
452   226.0     0.1725
453   226.5     0.1723
454   227.0     0.1724
455   227.5     0.1725
456   228.0     0.1728
457   228.5     0.1730
458   229.0     0.1730
459   229.5     0.1728
460   230.0     0.1728
461   230.5     0.1724
462   231.0     0.1723
463   231.5     0.1719
464   232.0     0.1721
465   232.5     0.1724
466   233.0     0.1725
467   233.5     0.1725
468   234.0     0.1726
469   234.5     0.1727
470   235.0     0.1726
471   235.5     0.1723
472   236.0     0.1725
473   236.5     0.1723
474   237.0     0.1723
475   237.5     0.1722
476   238.0     0.1724
477   238.5     0.1725
478   239.0     0.1726
479   239.5     0.1730
480   240.0     0.1730
481   240.5     0.1728
482   241.0     0.1728
483   241.5     0.1729
484   242.0     0.1728
485   242.5     0.1726
486   243.0     0.1726
487   243.5     0.1723
488   244.0     0.1718
489   244.5     0.1717
490   245.0     0.1717
491   245.5     0.1721
492   246.0     0.1722
493   246.5     0.1724
494   247.0     0.1723
495   247.5     0.1724
496   248.0     0.1724
497   248.5     0.1723
498   249.0     0.1723
499   249.5     0.1725
500   250.0     0.1724
501   250.5     0.1726
502   251.0     0.1723
503   251.5     0.1720
504   252.0     0.1721
505   252.5     0.1721
506   253.0     0.1723
507   253.5     0.1722
508   254.0     0.1721
509   254.5     0.1719
510   255.0     0.1718
511   255.5     0.1717
512   256.0     0.1718
513   256.5     0.1723
514   257.0     0.1723
515   257.5     0.1726
516   258.0     0.1730
517   258.5     0.1730
518   259.0     0.1728
519   259.5     0.1726
520   260.0     0.1726
521   260.5     0.1725
522   261.0     0.1721
523   261.5     0.1721
524   262.0     0.1722
525   262.5     0.1723
526   263.0     0.1723
527   263.5     0.1721
528   264.0     0.1721
529   264.5     0.1722
530   265.0     0.1722
531   265.5     0.1722
532   266.0     0.1724
533   266.5     0.1721
534   267.0     0.1720
535   267.5     0.1721
536   268.0     0.1722
537   268.5     0.1723
538   269.0     0.1724
539   269.5     0.1723
540   270.0     0.1725
541   270.5     0.1725
542   271.0     0.1723
543   271.5     0.1724
544   272.0     0.1724
545   272.5     0.1724
546   273.0     0.1724
547   273.5     0.1723
548   274.0     0.1721
549   274.5     0.1718
550   275.0     0.1718
551   275.5     0.1720
552   276.0     0.1716
553   276.5     0.1719
554   277.0     0.1719
555   277.5     0.1720
556   278.0     0.1721
557   278.5     0.1721
558   279.0     0.1722
559   279.5     0.1722
560   280.0     0.1721
561   280.5     0.1720
562   281.0     0.1720
563   281.5     0.1721
564   282.0     0.1721
565   282.5     0.1721
566   283.0     0.1719
567   283.5     0.1720
568   284.0     0.1723
569   284.5     0.1722
570   285.0     0.1721
571   285.5     0.1722
572   286.0     0.1725
573   286.5     0.1726
574   287.0     0.1728
575   287.5     0.1730
576   288.0     0.1733
577   288.5     0.1736
578   289.0     0.1737
579   289.5     0.1737
580   290.0     0.1738
581   290.5     0.1740
582   291.0     0.1740
583   291.5     0.1739
584   292.0     0.1739
585   292.5     0.1735
586   293.0     0.1734
587   293.5     0.1731
588   294.0     0.1732
589   294.5     0.1730
590   295.0     0.1729
591   295.5     0.1730
592   296.0     0.1731
593   296.5     0.1728
594   297.0     0.1727
595   297.5     0.1725
596   298.0     0.1722
597   298.5     0.1719
598   299.0     0.1717
599   299.5     0.1720
600   300.0     0.1722
601   300.5     0.1722
602   301.0     0.1723
603   301.5     0.1722
604   302.0     0.1722
605   302.5     0.1722
606   303.0     0.1721
607   303.5     0.1719
608   304.0     0.1722
609   304.5     0.1721
610   305.0     0.1721
611   305.5     0.1719
612   306.0     0.1719
613   306.5     0.1718
614   307.0     0.1718
615   307.5     0.1720
616   308.0     0.1720
617   308.5     0.1719
618   309.0     0.1720
619   309.5     0.1723
620   310.0     0.1725
621   310.5     0.1727
622   311.0     0.1726
623   311.5     0.1726
624   312.0     0.1725
625   312.5     0.1725
626   313.0     0.1727
627   313.5     0.1727
628   314.0     0.1724
629   314.5     0.1726
630   315.0     0.1725
631   315.5     0.1725
632   316.0     0.1725
633   316.5     0.1723
634   317.0     0.1725
635   317.5     0.1724
636   318.0     0.1722
637   318.5     0.1720
638   319.0     0.1718
639   319.5     0.1716
640   320.0     0.1718
641   320.5     0.1720
642   321.0     0.1718
643   321.5     0.1717
644   322.0     0.1716
645   322.5     0.1716
646   323.0     0.1718
647   323.5     0.1721
648   324.0     0.1724
649   324.5     0.1724
650   325.0     0.1724
651   325.5     0.1722
652   326.0     0.1721
653   326.5     0.1722
654   327.0     0.1721
655   327.5     0.1720
656   328.0     0.1717
657   328.5     0.1716
658   329.0     0.1720
659   329.5     0.1722
660   330.0     0.1724
661   330.5     0.1725
662   331.0     0.1724
663   331.5     0.1724
664   332.0     0.1724
665   332.5     0.1725
666   333.0     0.1723
667   333.5     0.1722
668   334.0     0.1723
669   334.5     0.1725
670   335.0     0.1724
671   335.5     0.1727
672   336.0     0.1727
673   336.5     0.1728
674   337.0     0.1725
675   337.5     0.1728
676   338.0     0.1726
677   338.5     0.1727
678   339.0     0.1729
679   339.5     0.1727
680   340.0     0.1726
681   340.5     0.1728
682   341.0     0.1730
683   341.5     0.1728
684   342.0     0.1727
685   342.5     0.1726
686   343.0     0.1725
687   343.5     0.1725
688   344.0     0.1725
689   344.5     0.1724
690   345.0     0.1721
691   345.5     0.1721
692   346.0     0.1720
693   346.5     0.1721
694   347.0     0.1722
695   347.5     0.1720
696   348.0     0.1718
697   348.5     0.1721
698   349.0     0.1724
699   349.5     0.1724
700   350.0     0.1722
701   350.5     0.1725
702   351.0     0.1727
703   351.5     0.1728
704   352.0     0.1726
705   352.5     0.1724
706   353.0     0.1724
707   353.5     0.1722
708   354.0     0.1722
709   354.5     0.1722
710   355.0     0.1720
711   355.5     0.1720
712   356.0     0.1721
713   356.5     0.1722
714   357.0     0.1722
715   357.5     0.1724
716   358.0     0.1726
717   358.5     0.1727
718   359.0     0.1725
719   359.5     0.1724
720   360.0     0.1724
721   360.5     0.1724
722   361.0     0.1723
723   361.5     0.1722
724   362.0     0.1722
725   362.5     0.1722
726   363.0     0.1720
727   363.5     0.1717
728   364.0     0.1717
729   364.5     0.1718
730   365.0     0.1718
731   365.5     0.1721
732   366.0     0.1720
733   366.5     0.1719
734   367.0     0.1720
735   367.5     0.1720
736   368.0     0.1720
737   368.5     0.1721
738   369.0     0.1722
739   369.5     0.1723
740   370.0     0.1723
741   370.5     0.1722
742   371.0     0.1722
743   371.5     0.1721
744   372.0     0.1717
745   372.5     0.1716
746   373.0     0.1715
747   373.5     0.1715
748   374.0     0.1717
749   374.5     0.1718
750   375.0     0.1719
751   375.5     0.1717
752   376.0     0.1719
753   376.5     0.1716
754   377.0     0.1714
755   377.5     0.1715
756   378.0     0.1713
757   378.5     0.1710
758   379.0     0.1712
759   379.5     0.1710
760   380.0     0.1706
761   380.5     0.1706
762   381.0     0.1707
763   381.5     0.1710
764   382.0     0.1713
765   382.5     0.1714
766   383.0     0.1712
767   383.5     0.1717
768   384.0     0.1721
769   384.5     0.1718
770   385.0     0.1717
771   385.5     0.1716
772   386.0     0.1717
773   386.5     0.1717
774   387.0     0.1714
775   387.5     0.1717
776   388.0     0.1716
777   388.5     0.1715
778   389.0     0.1714
779   389.5     0.1712
780   390.0     0.1709
781   390.5     0.1709
782   391.0     0.1709
783   391.5     0.1709
784   392.0     0.1711
785   392.5     0.1711
786   393.0     0.1711
787   393.5     0.1712
788   394.0     0.1713
789   394.5     0.1713
790   395.0     0.1713
791   395.5     0.1709
792   396.0     0.1708
793   396.5     0.1708
794   397.0     0.1708
795   397.5     0.1706
796   398.0     0.1707
797   398.5     0.1707
798   399.0     0.1707
799   399.5     0.1705
800   400.0     0.1705
801   400.5     0.1708
802   401.0     0.1713
803   401.5     0.1717
804   402.0     0.1717
805   402.5     0.1717
806   403.0     0.1715
807   403.5     0.1715
808   404.0     0.1714
809   404.5     0.1713
810   405.0     0.1718
811   405.5     0.1719
812   406.0     0.1718
813   406.5     0.1716
814   407.0     0.1716
815   407.5     0.1719
816   408.0     0.1722
817   408.5     0.1727
818   409.0     0.1726
819   409.5     0.1723
820   410.0     0.1719
821   410.5     0.1716
822   411.0     0.1716
823   411.5     0.1715
824   412.0     0.1715
825   412.5     0.1717
826   413.0     0.1718
827   413.5     0.1718
828   414.0     0.1717
829   414.5     0.1716
830   415.0     0.1716
831   415.5     0.1717
832   416.0     0.1718
833   416.5     0.1717
834   417.0     0.1718
835   417.5     0.1716
836   418.0     0.1714
837   418.5     0.1712
838   419.0     0.1711
839   419.5     0.1712
840   420.0     0.1711
841   420.5     0.1711
842   421.0     0.1712
843   421.5     0.1713
844   422.0     0.1714
845   422.5     0.1714
846   423.0     0.1714
847   423.5     0.1712
848   424.0     0.1711
849   424.5     0.1710
850   425.0     0.1712
851   425.5     0.1711
852   426.0     0.1711
853   426.5     0.1716
854   427.0     0.1718
855   427.5     0.1719
856   428.0     0.1718
857   428.5     0.1717
858   429.0     0.1717
859   429.5     0.1715
860   430.0     0.1712
861   430.5     0.1711
862   431.0     0.1708
863   431.5     0.1709
864   432.0     0.1710
865   432.5     0.1713
866   433.0     0.1711
867   433.5     0.1710